services:
  chrome:
    image: lscr.io/linuxserver/chrome:latest
    container_name: chrome
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-Europe/Madrid}
    volumes:
      - chrome_config:/config
    ports:
      - "3000:3000"  # Web UI
      - "3001:3001"  # VNC
    restart: unless-stopped

volumes:
  chrome_config: